[project]
name = "ecb-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "patito>=0.8.5",
    "polars>=1.34.0",
    "streamlit>=1.50.0",
]
